opendatacam/opendatacam

docker/install-opendatacam.sh
docker/run-nvidia-docker/run-nvidiadocker.sh
documentation/CONFIG.md

Evo: simplify install script + add documentation to mount usbcam for nvidiadocker

---

docker/install-opendatacam.sh
docker/run-nvidia-docker/run-nvidiadocker.sh

add '--device=/dev/video0:/dev/video0` on nvidiadocker script
#102

Add usb device (default is video0) to nvidiadocker script

---

components/canvas/engines/LiveViewEngine.js

UI fix by @b-g , related to https://github.com/opendatacam/opendatacam/issues/96

Fix: avoid overlapping text in bbox labels

---

README.md

Added the Webcam Logitech C310 to the documentation.
I am using C310 and it works fine out of box.

added C310 to cam

---

docker/install-opendatacam.sh

It would be easier to automatically start/stop the container if it has specific name, instead of a random one

specify the name of the docker container

---

server/Opendatacam.js

let's see if this improve https://github.com/opendatacam/opendatacam/issues/204

Improve counting logic #204

---

server.js

Example of exported CSV file:
```
frameId,timestamp,area,name,id,bearing,countingDirection,angleWithCountingLine
434,"2020-08-15T13:44:10.420Z","test","car",6,182.6025622024998,"leftright_topbottom",87.32321862595369
451,"2020-08-15T13:44:11.303Z","test","car",7,167.0053832080835,"leftright_topbottom",77.07960237963002
603,"2020-08-15T13:44:19.561Z","test","car",17,194.34933204294714,"leftright_topbottom",75.57644878550634
618,"2020-08-15T13:44:20.344Z","test","car",23,196.26020470831196,"leftright_topbottom",73.66557612014152
```

Fix(CSV): Export Headers

---

config.json
documentation/CONFIG.md
package-lock.json
package.json
server/Opendatacam.js

Including making `fastDelete` configurable from OpenDataCam config.
Closes #269

Feat(Tracker): Bump to node-moving-things-tracker v0.8.0

---

config.json
documentation/CONFIG.md
server.js

Closes https://github.com/opendatacam/opendatacam/issues/273

Fix(GPS): Fixes typo in csvExportOpenStreeetMapsUrl

---

server.js

Closes https://github.com/opendatacam/opendatacam/issues/285

Fix(Server): Correct name and extension for tracker and counter

---

server.js
server/Opendatacam.js

Closes https://github.com/opendatacam/opendatacam/issues/288

Refactor(Tracker): Init tracker config on startup

---

server/Opendatacam.js

Closes https://github.com/opendatacam/opendatacam/issues/290

Fix(Opendatacam): Log SSE changes only once

---

server/Opendatacam.js

Closes https://github.com/opendatacam/opendatacam/issues/217

Fix(Opendatacam): Correctly calculate the number of tracked items

---

server.js

docs(server): Re-Adds docstring to /webcam/stream

---

server.js
server/Opendatacam.js

(and take care of deleting them from the set once they close)

Allow multiple SSE connections

---

server/utils/mjpegproxy.js

`chunk` is already a buffer, so the conversion isn't needed :)
also, change `http.request()` + `request.end()` to an `http.get()` call

some nits in mjpeg-proxy

---

server/Opendatacam.js

- make sure all errors are handled
- always log the stream error, except for ECONNREFUSED
- reindent the code
- put the return condition above (to remove indentation)

fix(YOLO): some refactoring

---

server/Opendatacam.js

313 fix opendatacam yolo error handling

---

documentation/CONFIG.md

Hi,
I have added some instructions for custom model implementation.

Add instructions for custom model implementation

---

README.md
docker/install-opendatacam.sh
docker/run/desktop/kubernetes/0001-mongodb-deployment.yaml
docker/run/desktop/kubernetes/0002-opendatacam-deployment.yaml
docker/run/nano/kubernetes/0001-mongodb-deployment.yaml
docker/run/nano/kubernetes/0002-opendatacam-deployment.yaml
docker/run/xavier/kubernetes/0001-mongodb-deployment.yaml
docker/run/xavier/kubernetes/0002-opendatacam-deployment.yaml
documentation/CONFIG.md
documentation/DEVELOPMENT_NOTES.md

I've noticed that there are commits in `master` which are not yet in `development`. This PR should bring them back in sync.

Chore: master to development

---

scripts/YoloSimulation.js
scripts/removeFPS.js

To verify that no eslint warnings remain merge https://github.com/opendatacam/opendatacam/pull/331 and re-run the checks for this pull-request.

style(scripts): Fixes eslint warnings

---

spec/helpers/env.js
spec/scripts/YoloSimulation.spec.js
spec/server/db/DBManager.spec.js
spec/server/processes/YoloDarknet.spec.js
spec/server/utils/configHelper.spec.js

To verify that no eslint warnings remain merge https://github.com/opendatacam/opendatacam/pull/331 and re-run the checks for this pull-request.

style(spec): Fixes all eslint warnings

---

server.js

This fixes most eslint warnings for the `server.js` file. As there are a lot of styling and whitespace changes I tried to split the changes into multiple PRs to make them easier to review.
As there are a lot of [no-console](https://eslint.org/docs/rules/no-console) warnings which I will leave there until we get around to https://github.com/opendatacam/opendatacam/issues/275
To verify that no eslint warnings remain merge #331 and re-run the checks for this pull-request.

Chore eslint fix serverjs

---

documentation/DEVELOPMENT_NOTES.md

merging this to have all the commits of master into development .. it was a test to see if it was deploying the static pages.. but as the github action isn't on master it doesn't work yet ;-)

Evo: update development notes to test github page docs action

---

statemanagement/app/AppStateManagement.js
statemanagement/app/CounterStateManagement.js
statemanagement/app/HistoryStateManagement.js
statemanagement/app/TrackerStateManagement.js
statemanagement/app/UserSettingsStateManagement.js
statemanagement/app/ViewportStateManagement.js
statemanagement/reducers.js
statemanagement/store.js

14 warnings remain which are not straightforward to fix and need to be tackled another day

Refactor: fixes most eslint warnings for statemanagement

---

.eslintrc.json
components/dataview/Recording.js
components/shared/CounterAreasVisualizer.js
pages/_app.js
pages/index.js
postcss.config.js
server/Opendatacam.js
server/fs/FileSystemManager.js
server/processes/YoloDarknet.js
server/test/listenToYOLO.js
server/test/mjpeg.js
server/tracker/utils.js
server/utils/Logger.js
server/utils/mjpegproxy.js
server/utils/urlHelper.js
tailwind.config.js

This should remove all "low hanging" warnings. The total number is down to 1237 warnings (from initially 5441 warnings) 🥳

Refactor: Runs eslint --fix on rest of codebase

---

server.js

Fix CSV export

---

server.js
server/db/MongoDbManager.js
spec/server/db/MongoDbManager.spec.js

Reconnect to MongoDB on connection loss

---

.dockerignore
docker/build/desktop/Dockerfile
docker/build/nano/Dockerfile
docker/build/xavier/Dockerfile
scripts/npm/build.sh
scripts/npm/generateapidoc.sh
scripts/npm/lint.sh
scripts/npm/startServer.sh
scripts/npm/test.sh

Attemps to remove unused files from the docker image such as the `.git` folder.

fix(docker): Trim Docker Image

---

docker/build/desktop/Dockerfile
docker/build/nano/Dockerfile
docker/build/xavier/Dockerfile

fix(docker): Fixes default neural network to right settings

---

server.js

Closes https://github.com/opendatacam/opendatacam/issues/396

Fix(server): Return 404 if recording not found

---

package-lock.json
package.json

Closes https://github.com/opendatacam/opendatacam/issues/410

Chore: Uses node-moving-things-tracker@0.8.1

---

docker/build/desktop/Dockerfile
docker/build/nano/Dockerfile
docker/build/xavier/Dockerfile

Closes https://github.com/opendatacam/opendatacam/issues/436

Chore: Build ODC Docker Image from Darknet Release

---

documentation/USE_WITHOUT_DOCKER.md

The original may have been by design, but I spent awhile looking for the directory open-data-cam even though I figured I needed to get into opendatacam for npm. Anyway, I removed the hyphens for clarity. My very small contribution to such an amazing project that I do hope to be able to contribute more as I learn it better.
> Awesome! Can you rebase against development? Otherwise looks good and I'll merge it +1
Rebase failed for some reason so resubmitting

Updated Use without docker instructions

---

.github/workflows/ci-cd.yml
package-lock.json
package.json

Fix NPM and Node Dependencies

---

scripts/npm/generateapidoc.sh

476 apidoc warning

---

scripts/YoloSimulation.js

511 darknet simulation live

---

server/Opendatacam.js
server/processes/YoloDarknet.js
server/utils/mjpegproxy.js
spec/server/processes/YoloDarknet.spec.js

This takes input from https://github.com/opendatacam/opendatacam/pull/492 to fix the darknet reconnect issue. The following things are different from https://github.com/opendatacam/opendatacam/pull/492
- No need to change config.json
- MJPEG properly detects and handles darknet reconnects
Closes #368

368 darknet reconnect

---

server.js

404 file upload broken

---

config.json
documentation/CONFIG.md
package-lock.json
package.json
server.js

node-moving-things v0.9.0

---

scripts/YoloSimulation.js
server/processes/YoloDarknet.js
spec/scripts/YoloSimulation.spec.js
spec/server/processes/YoloDarknet.spec.js

YoloSimulation keep streaming json even without images

---

package-lock.json
package.json

Next v9 was getting a bit old and Next 10 could be upgraded to without
any breaking changes according to https://nextjs.org/docs/upgrading#upgrading-from-version-9-to-10
See also #485

Feat: Update to NextJS 10

---

package-lock.json
package.json
server.js
server/Opendatacam.js
spec/server/Opendatacam.spec.js

Fixes Memory Leak

---

docker/build/desktop/Dockerfile
docker/build/nano/Dockerfile
docker/build/xavier/Dockerfile

Closes https://github.com/opendatacam/opendatacam/issues/541

Fixes NVIDIA signing key changes

---

config.json

Closes https://github.com/opendatacam/opendatacam/issues/542

Fix: Only track counted classes

---

components/shared/WebcamStream.js
server/utils/mjpegproxy.js

Closes https://github.com/opendatacam/opendatacam/issues/547

Fix: Don't show grey screen when UI starts

---

.github/workflows/ci-cd.yml
docker/build/cpu-amd64/Dockerfile
docker/build/cpu-amd64/launch.sh
docker/build/desktop/Dockerfile
docker/build/nano/Dockerfile
docker/build/xavier/Dockerfile

Use v1.1.0-odc-Yolo-v3

---

scripts/YoloSimulation.js

Yolo Simulation in Live Mode does not increment frame ID correctly

---

components/canvas/engines/PathViewEngine.js

Path View: Keep color if ID does not change

---

server/utils/urlHelper.js

Fix urlHelper
